add supporting for corvus proxy
HunanTV/redis-ctl pull request #25
Opened 2016-10-14 09:32 UTC by jasonjoo2010

2016-10-17 02:19 UTC, zheplusplus requested changes

2016-10-17 02:19 UTC, neuront commented on app/bps/cluster.py
> +        cmd = ['proxy', 'setremotes']
建议此处不要使用 magic number, 而在 models.proxy 里定义 `TYPE_CORVUS` `TYPE_CERBERUS` 之类的常量

2016-10-17 02:19 UTC, neuront commented on dbver/versions/00002_proxy_type.py
> +    proxy.create_column(proxy_type_column)
`server_default` 为什么是字符串? (是 sqlalchemy_migration 要求的吗?)

2016-10-17 02:19 UTC, neuront commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
此处修改与 corvus 支持并无关系? 建议分开提交

2016-10-17 02:19 UTC, neuront commented on models/node.py
>      return node
如果有重复记录会抛出 `IntegrityError` 使得插入失败的.

2016-10-17 02:19 UTC, neuront commented on models/stats_base.py
> +
去掉行尾空格

2016-10-17 02:19 UTC, neuront commented on models/stats_base.py
> +            self.typename = 'Cerberus'
应使用整数常量名而不是字符串比较

2016-10-17 03:11 UTC, jasonjoo2010 commented on dbver/versions/00002_proxy_type.py
> +    proxy.create_column(proxy_type_column)
Column中对server_default貌似只接受特定的类型, 和字符串,  不然报无法处理的类型.
而最终拼接进ddl中时,  default '1' 等效于 default 1,  类似 insert into (id) values ('1'),  当然这样也给转义带来了优势.

2016-10-17 03:14 UTC, jasonjoo2010 commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
这个是顺手解决的bug,  在错误的模式的redis或并不存在的redis时会出错

2016-10-17 03:15 UTC, jasonjoo2010 commented on models/node.py
>      return node
这个主要考虑点是范围添加时, 一旦碰到错误即会终止, 所以跟前端一起配合使用了较为优雅的输出和处理

2016-10-17 03:16 UTC, jasonjoo2010 commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
所以这个修改要拆开吗？因为涉及了js、模板和相关处理后端

2016-10-17 06:29 UTC, zheplusplus commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
好, 姑且先合进来... 这样写 magic number 作为 status 的值 是不建议的, 先把 bug 修了再看看怎么调整.

2016-10-17 06:36 UTC, jasonjoo2010 commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
这个地方的status本来确实不是这样的,  但在使用route_post时, 采用状态码判断错误和描述后, route_post没有更新poll的功能, 权衡了下后来就继续沿用了route_post_json.

看了下route_post_json里面状态码是死的,  没办法自定义,  这个你建议怎么改？增加一个route_post带参版还是让route_post_json有改变状态码的功能？

2016-10-17 07:35 UTC, neuront commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
目前就放在字典数据里返回吧.

之后打算改掉 添加 Redis 的页面的结构, 输入 Redis 地址和端口号范围之后列出待加入的 Redis, 并通过服务器发一个 INFO 看看情况, 确认后再添加.

2016-10-17 10:06 UTC, jasonjoo2010 commented on app/bps/redis.py
> +    return {'reason': reason, 'status': status}
ok, 目前的bug也提交了,  这个review需要我操作吗？

2016-10-18 02:06 UTC, zheplusplus commented on daemonutils/stats_models.py
> +                    pass
这样设一个 key 不好吧, 有其他方法检查么? 或者 corvus 暂时就都默认 cluster_ok=1 (老版本的 cerberus 也没这一项)

2016-10-18 02:06 UTC, neuront commented on dbver/versions/00001_init.py
>      mysql_engine='InnoDB', mysql_charset='utf8'
为什么这些列的属性被改掉?

2016-10-18 02:06 UTC, neuront commented on models/stats_base.py
> +
行尾空格

2016-10-18 02:13 UTC, jasonjoo2010 commented on daemonutils/stats_models.py
> +                    pass
这个我询问一下corus项目组, 稍候更新

2016-10-18 03:57 UTC, jasonjoo2010 commented on dbver/versions/00001_init.py
>      mysql_engine='InnoDB', mysql_charset='utf8'
因为系统较多使用了数据库层面的外键, 在一些插入数据但无法确认值的场景中, 外键列非空会导致无法插入, 这种情况下只能改回允许空, 所以初始版本我对照了下之前的sql, 逐一把需要空的列改了一遍, 这回应该都是可以的了, 与当前库是一致的

2016-10-18 03:57 UTC, jasonjoo2010 commented on daemonutils/stats_models.py
> +                    pass
这个询问后Corvus不检查cluster状态, 所以我先改恒值吧

2016-10-18 04:04 UTC, jasonjoo2010 commented on dbver/versions/00001_init.py
>      mysql_engine='InnoDB', mysql_charset='utf8'
另外还少了一张表,  见Issue

2017-01-05 11:43 UTC, jasonjoo2010 commented
@neuront  这个PR还有变更要做么？

2017-01-06 00:11 UTC, neuront commented on dbver/versions/00001_init.py
>      mysql_engine='InnoDB', mysql_charset='utf8'
你后来关了那个 issue, 所以还是少了一张表么, 以及如果那个 issue 不成立, 这些列的约束就应该改回去吧?

2017-01-06 02:52 UTC, jasonjoo2010 commented on dbver/versions/00001_init.py
>      mysql_engine='InnoDB', mysql_charset='utf8'
@neuront  这个container后续会进行实现,  目前就是按老的sql文件里面描述的那样,  先允许空处理,  所以不影响

2017-01-07 02:53 UTC, merged